using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using TegoareWeb.Data;
using TegoareWeb.Models;

namespace TegoareWeb.Controllers
{
    public class SeedController : Controller
    {
        private readonly TegoareContext _context;
        static String strStatus="Kies een actie";

        public SeedController(TegoareContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewData["status"] = strStatus;
            return View();
        }

        public async Task<IActionResult> DelGroepen()
        {
            _context.Groepen.RemoveRange(_context.Groepen);
             await _context.SaveChangesAsync();
            strStatus = "Groepen zijn gewist";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> SeedGroepen()
        {
            _context.Groepen.Add(new Groep { Rol = "Vrijwilliger", Omschrijving = "Helpt mee met activiteiten" });
            _context.Groepen.Add(new Groep { Rol = "Gezinshoofd", Omschrijving = "Verantwoordelijke van een gezin. Kan de eigen gegevens aanpassen en de gegevens van anderen van het gezin." });
            _context.Groepen.Add(new Groep { Rol = "Activiteitenmanager", Omschrijving = "Kan activiteiten aanmaken/verwijderen/aanpassen" });
            _context.Groepen.Add(new Groep { Rol = "Huisbezoeker", Omschrijving = "Kan zijn eigen gegevens aanpassen en de gegevens van de personen waar hij verantwoordelijk voor is" });
            _context.Groepen.Add(new Groep { Rol = "Stuurgroep", Omschrijving = "Zit in het beheer van de vzw" });
            _context.Groepen.Add(new Groep { Rol = "Ledenbeheerder", Omschrijving = "Kan de gegevens van iedere persoon in de database aanpassen/aanmaken/verwijderen" });
            
            await _context.SaveChangesAsync();
            strStatus = "Groepen zijn opnieuw aangemaakt";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DelLeden()
        {
            _context.Leden.RemoveRange(_context.Leden);
            await _context.SaveChangesAsync();
            strStatus = "Leden zijn gewist";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> SeedLeden()
        {
            //            _context.Leden.Add(new Lid { Achternaam = "Tester", Voornaam = "Voornaam", Geboortedatum = DateTime.Parse("31/12/1974", new CultureInfo("de-DE")), Straatnaam = "RvBlaan", Straatnummer = "182", Postcode= 8900, Gemeente = "IEPER", Telefoon_vast = "057/123456", Telefoon_GSM = "0498/123456", Email = "anckaert.peter@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Vanhauwaert", Voornaam = "Marcel", Geboortedatum = DateTime.Parse("19/01/1938", new CultureInfo("de-DE")), Straatnaam = "Groenestraat", Straatnummer = "22", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/205070", Telefoon_GSM = "", Email = "ria.coulembier@belgacom.net" });
            _context.Leden.Add(new Lid { Achternaam = "Saelens ", Voornaam = "Josiane", Geboortedatum = DateTime.Parse("20/06/1959", new CultureInfo("de-DE")), Straatnaam = "R.Van Bethunelaan", Straatnummer = "84", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/218440", Telefoon_GSM = "0471/024017", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Seghers ", Voornaam = "Nicole", Geboortedatum = DateTime.Parse("28/12/1959", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "50", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/216537", Telefoon_GSM = "0486/866517", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Sesztak ", Voornaam = "Scaba", Geboortedatum = DateTime.Parse("23/09/1954", new CultureInfo("de-DE")), Straatnaam = "Cartonstraat", Straatnummer = "34", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/206987", Telefoon_GSM = "0474/324706", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Depoortere ", Voornaam = "José", Geboortedatum = DateTime.Parse("16/04/1951", new CultureInfo("de-DE")), Straatnaam = "Lindendreef", Straatnummer = "50", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/468801", Telefoon_GSM = "0471/341149", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandercruysse ", Voornaam = "Magda", Geboortedatum = DateTime.Parse("19/05/1958", new CultureInfo("de-DE")), Straatnaam = "Wateringstraat", Straatnummer = "20", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0485/706663", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Lefevere ", Voornaam = "Daniël", Geboortedatum = DateTime.Parse("06/02/1946", new CultureInfo("de-DE")), Straatnaam = "Torrepoortlaan", Straatnummer = "61", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/422086", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Verschoore ", Voornaam = "Ingrid", Geboortedatum = DateTime.Parse("04/03/1955", new CultureInfo("de-DE")), Straatnaam = "Pilkemseweg", Straatnummer = "75", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0474/941240", Email = "ingrid.verschoore@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Wyffels ", Voornaam = "Bieke", Geboortedatum = DateTime.Parse("23/11/1978", new CultureInfo("de-DE")), Straatnaam = "R.Vanbethunelaan", Straatnummer = "182", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0478/653930", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Ankaert ", Voornaam = "Peter", Geboortedatum = DateTime.Parse("11/03/1974", new CultureInfo("de-DE")), Straatnaam = "R.Vanbethunelaan", Straatnummer = "182", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/363854", Telefoon_GSM = "0498/631157", Email = "anckaert.peter@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Wyffels ", Voornaam = "Mayté", Geboortedatum = DateTime.Parse("03/08/2005", new CultureInfo("de-DE")), Straatnaam = "R.Vanbethunelaan", Straatnummer = "182", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Ankaert ", Voornaam = "Brian", Geboortedatum = DateTime.Parse("02/10/2009", new CultureInfo("de-DE")), Straatnaam = "R.Vanbethunelaan", Straatnummer = "182", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Beun ", Voornaam = "Noël", Geboortedatum = DateTime.Parse("06/02/1959", new CultureInfo("de-DE")), Straatnaam = "Langemarkstraat", Straatnummer = "6/001 glv", Postcode = 8980, Gemeente = "Zonnebeke", Telefoon_vast = "057/365602", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Wicke ", Voornaam = "Nicole", Geboortedatum = DateTime.Parse("29/06/1933", new CultureInfo("de-DE")), Straatnaam = "Lindendreef", Straatnummer = "48", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/218580", Telefoon_GSM = "0477/361042", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Manuella ", Voornaam = "Cauwelier", Geboortedatum = DateTime.Parse("10/01/1980", new CultureInfo("de-DE")), Straatnaam = "R. Van Bethunelaan", Straatnummer = "33", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/300998", Telefoon_GSM = "0470/612939", Email = "meilsa-laforce@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Laforce ", Voornaam = "Melissa", Geboortedatum = DateTime.Parse("20/05/2002", new CultureInfo("de-DE")), Straatnaam = "R. Van Bethunelaan", Straatnummer = "33", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Laforce ", Voornaam = "Mandy", Geboortedatum = DateTime.Parse("04/06/2003", new CultureInfo("de-DE")), Straatnaam = "R. Van Bethunelaan", Straatnummer = "33", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Laforce ", Voornaam = "Milan", Geboortedatum = DateTime.Parse("09/09/2004", new CultureInfo("de-DE")), Straatnaam = "R. Van Bethunelaan", Straatnummer = "33", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Laforce ", Voornaam = "Mickie", Geboortedatum = DateTime.Parse("14/12/2005", new CultureInfo("de-DE")), Straatnaam = "R. Van Bethunelaan", Straatnummer = "33", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Laforce ", Voornaam = "Madison", Geboortedatum = DateTime.Parse("16/06/2010", new CultureInfo("de-DE")), Straatnaam = "R. Van Bethunelaan", Straatnummer = "33", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Mussche ", Voornaam = "Dorine", Geboortedatum = DateTime.Parse("05/06/1968", new CultureInfo("de-DE")), Straatnaam = "Voedermonthoeve", Straatnummer = "1", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0494/627875", Email = "dorine.mussche@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Coulembier ", Voornaam = "Talitha", Geboortedatum = DateTime.Parse("07/10/1998", new CultureInfo("de-DE")), Straatnaam = "Voedermonthoeve", Straatnummer = "1", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0491/427400", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Coulembier ", Voornaam = "Aïsha", Geboortedatum = DateTime.Parse("06/06/2001", new CultureInfo("de-DE")), Straatnaam = "Voedermonthoeve", Straatnummer = "1", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Goudezeune ", Voornaam = "Dinora", Geboortedatum = DateTime.Parse("30/03/1957", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "32", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0491/746517", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Goudezeune ", Voornaam = "Graziano", Geboortedatum = DateTime.Parse("20/05/1998", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "32", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0495/285959", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Verpoot ", Voornaam = "Melina-bijManuella", Geboortedatum = DateTime.Parse("19/07/1991", new CultureInfo("de-DE")), Straatnaam = "Rijselstraat", Straatnummer = "182 glv A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0491/306211", Email = "verpootm7@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Verpoot ", Voornaam = "Yassira", Geboortedatum = DateTime.Parse("26/09/2015", new CultureInfo("de-DE")), Straatnaam = "Rijselstraat", Straatnummer = "182 glv A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Reynaert", Voornaam = "Kris", Geboortedatum = DateTime.Parse("06/02/1954", new CultureInfo("de-DE")), Straatnaam = "Frezenbergstraat", Straatnummer = "18", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/207666", Telefoon_GSM = "0473/642032", Email = "krisreynaert@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "De Wilde ", Voornaam = "Marcelle", Geboortedatum = DateTime.Parse("29/11/1950", new CultureInfo("de-DE")), Straatnaam = "Wieltjesgracht", Straatnummer = "kamernr 212", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/422799", Telefoon_GSM = "0471/863205", Email = "Residentie Ten Vesten" });
            _context.Leden.Add(new Lid { Achternaam = "mannenopvang ", Voornaam = "", Straatnaam = "Lombaertstraat", Straatnummer = "49", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/220930", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Somers ", Voornaam = "Katrien", Geboortedatum = DateTime.Parse("29/01/1970", new CultureInfo("de-DE")), Straatnaam = "Rozenlaan", Straatnummer = "12", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/366711", Telefoon_GSM = "0468/123250", Email = "Katrien458@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Verschaeve ", Voornaam = "Kris", Geboortedatum = DateTime.Parse("29/04/1971", new CultureInfo("de-DE")), Straatnaam = "Rustenhove", Straatnummer = "", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0477/074236", Email = "krisverschaeve@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Demonie ", Voornaam = "Veronique", Geboortedatum = DateTime.Parse("20/09/1962", new CultureInfo("de-DE")), Straatnaam = "Bukkerstraat", Straatnummer = "5", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0499/415938", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Commeyne ", Voornaam = "Hilde", Geboortedatum = DateTime.Parse("23/06/1957", new CultureInfo("de-DE")), Straatnaam = "Lombaertstraat", Straatnummer = "21", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0497/262304", Email = "hilde.comeyne@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Nadereh ", Voornaam = "Mehrfar", Geboortedatum = DateTime.Parse("02/09/1971", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "16", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/390189", Telefoon_GSM = "0490/393649", Email = "Landen.s1971@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Alireza ", Voornaam = "Owjé", Geboortedatum = DateTime.Parse("12/10/2009", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "16", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Elina ", Voornaam = "Owjé", Geboortedatum = DateTime.Parse("29/03/2012", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "16", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Ogbeide ", Voornaam = "Monica", Geboortedatum = DateTime.Parse("26/06/1976", new CultureInfo("de-DE")), Straatnaam = "Elverdingestraat", Straatnummer = "65", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0465/792301", Email = "ogbeide.isoken@outlook.be" });
            _context.Leden.Add(new Lid { Achternaam = "Rotsaert ", Voornaam = "Rhema", Geboortedatum = DateTime.Parse("26/04/2011", new CultureInfo("de-DE")), Straatnaam = "Elverdingestraat", Straatnummer = "65", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Ogbeide ", Voornaam = "Rehan", Geboortedatum = DateTime.Parse("09/12/2015", new CultureInfo("de-DE")), Straatnaam = "Elverdingestraat", Straatnummer = "65", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Guceiemeka ", Voornaam = "Eluwa", Geboortedatum = DateTime.Parse("09/07/2008", new CultureInfo("de-DE")), Straatnaam = "Elverdingestraat", Straatnummer = "65", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Sylvie ", Voornaam = "Decoodt(rosa)", Geboortedatum = DateTime.Parse("11/03/1980", new CultureInfo("de-DE")), Straatnaam = "Vinkenlaan", Straatnummer = "7 3B", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0476/966430", Email = "sylviedecoodt@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Noyke ", Voornaam = "Deleye", Geboortedatum = DateTime.Parse("02/08/2011", new CultureInfo("de-DE")), Straatnaam = "Vinkenlaan", Straatnummer = "7 3B", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Nylah ", Voornaam = "Deleye", Geboortedatum = DateTime.Parse("26/10/2009", new CultureInfo("de-DE")), Straatnaam = "Vinkenlaan", Straatnummer = "7 3B", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Van Denbrande ", Voornaam = "An", Geboortedatum = DateTime.Parse("30/07/1975", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "44", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0494/188653", Email = "AnVandenBrande@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Deleye ", Voornaam = "Fran", Geboortedatum = DateTime.Parse("09/05/2008", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "44", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Demolder ", Voornaam = "Christa", Geboortedatum = DateTime.Parse("08/12/1958", new CultureInfo("de-DE")), Straatnaam = "Paddepoelstraat", Straatnummer = "17", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0477/269407", Email = "demolderchrista@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Eneman ", Voornaam = "Christine", Geboortedatum = DateTime.Parse("13/04/1963", new CultureInfo("de-DE")), Straatnaam = "Aardestraat", Straatnummer = "10", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0474/778090", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Paruys ", Voornaam = "Marina", Geboortedatum = DateTime.Parse("31/10/1960", new CultureInfo("de-DE")), Straatnaam = "Hommelhofstraat", Straatnummer = "3", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/206504", Telefoon_GSM = "0495/158143", Email = "paruysje@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Haedens ", Voornaam = "Carmen", Geboortedatum = DateTime.Parse("18/05/1962", new CultureInfo("de-DE")), Straatnaam = "Acacialaan", Straatnummer = "64", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/201334", Telefoon_GSM = "", Email = "carmenhaedens@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Butstraen ", Voornaam = "Annie", Geboortedatum = DateTime.Parse("02/02/1948", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "60", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/400989", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vereecke ", Voornaam = "Franky", Geboortedatum = DateTime.Parse("10/02/1965", new CultureInfo("de-DE")), Straatnaam = "Lombaertstraat", Straatnummer = "11 2b", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0478/619288", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Logghe ", Voornaam = "Chalina", Geboortedatum = DateTime.Parse("02/11/1995", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "20", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0491/468997", Email = "logghe.chalina@outlook.be" });
            _context.Leden.Add(new Lid { Achternaam = "Godswil ", Voornaam = "Jonathan", Geboortedatum = DateTime.Parse("01/01/1997", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "20", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Logghe ", Voornaam = "Noura", Geboortedatum = DateTime.Parse("28/03/2015", new CultureInfo("de-DE")), Straatnaam = "Kerselaar", Straatnummer = "20", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vansteenkiste ", Voornaam = "Stefaan", Straatnaam = "De Haerdestraat", Straatnummer = "15 1a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Petit ", Voornaam = "Marie-Paule(Mary)", Straatnaam = "Bukkerstraat", Straatnummer = "33", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0476/235337", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Haest ", Voornaam = "Kelly", Straatnaam = "Maltastraat", Straatnummer = "7", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0473/274626", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Haest ", Voornaam = "Iben", Geboortedatum = DateTime.Parse("10/12/2008", new CultureInfo("de-DE")), Straatnaam = "Maltastraat", Straatnummer = "7", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Desmet ", Voornaam = "Nathan", Geboortedatum = DateTime.Parse("13/09/2006", new CultureInfo("de-DE")), Straatnaam = "Maltastraat", Straatnummer = "7", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Desmet ", Voornaam = "Rosa", Geboortedatum = DateTime.Parse("19/01/1943", new CultureInfo("de-DE")), Straatnaam = "Patrijzenlaan", Straatnummer = "7", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/203024", Telefoon_GSM = "0472/690927", Email = "rosa.desmet@icloud.be" });
            _context.Leden.Add(new Lid { Achternaam = "Coulembier ", Voornaam = "Adri", Geboortedatum = DateTime.Parse("21/03/1961", new CultureInfo("de-DE")), Straatnaam = "Poperingseweg", Straatnummer = "93", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0490/395773", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Paunaad ", Voornaam = "Nenita", Geboortedatum = DateTime.Parse("28/07/1978", new CultureInfo("de-DE")), Straatnaam = "Poperingseweg", Straatnummer = "93", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Paunaad ", Voornaam = "Naika", Geboortedatum = DateTime.Parse("27/08/2006", new CultureInfo("de-DE")), Straatnaam = "Poperingseweg", Straatnummer = "93", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Verhaeghe ", Voornaam = "Elis", Geboortedatum = DateTime.Parse("11/10/1997", new CultureInfo("de-DE")), Straatnaam = "Poperingseweg", Straatnummer = "93", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Coulembier ", Voornaam = "Benjamin", Geboortedatum = DateTime.Parse("23/10/1990", new CultureInfo("de-DE")), Straatnaam = "Poperingseweg", Straatnummer = "93", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Decadt ", Voornaam = "Saskia", Geboortedatum = DateTime.Parse("06/05/1971", new CultureInfo("de-DE")), Straatnaam = "Narcissenlaan", Straatnummer = "2/bus 19", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0489/780043", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Deraedt ", Voornaam = "Michele", Geboortedatum = DateTime.Parse("21/12/1945", new CultureInfo("de-DE")), Straatnaam = "Narcissenlaan", Straatnummer = "2 bus 3A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/207212", Telefoon_GSM = "0486/977884", Email = "michele.deraedt@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Bossue ", Voornaam = "Patrick", Geboortedatum = DateTime.Parse("30/08/1954", new CultureInfo("de-DE")), Straatnaam = "Narcissenlaan", Straatnummer = "2/bus 33", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/364376", Telefoon_GSM = "0468/228675", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Michael ", Voornaam = "Boone", Geboortedatum = DateTime.Parse("02/03/1966", new CultureInfo("de-DE")), Straatnaam = "De Sterre", Straatnummer = "2 verdiep (2d)", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/421969", Telefoon_GSM = "0468/472809", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Duthoo ", Voornaam = "Rita", Geboortedatum = DateTime.Parse("23/03/1954", new CultureInfo("de-DE")), Straatnaam = "Fazantenlaan", Straatnummer = "15", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/201203", Telefoon_GSM = "0484/171205", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Ameele ", Voornaam = "Godelieve", Geboortedatum = DateTime.Parse("13/10/1945", new CultureInfo("de-DE")), Straatnaam = "Fazantenlaan", Straatnummer = "17 A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/366993", Telefoon_GSM = "0497/227353", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bouchaert ", Voornaam = "Claire", Geboortedatum = DateTime.Parse("22/02/1956", new CultureInfo("de-DE")), Straatnaam = "M. Haiglaan", Straatnummer = "50", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/206804", Telefoon_GSM = "0496/141556", Email = "claire.bouchaert@euphonynet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Vandersype ", Voornaam = "Laurette", Geboortedatum = DateTime.Parse("13/01/1960", new CultureInfo("de-DE")), Straatnaam = "Roodstaartplein", Straatnummer = "29", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/366863", Telefoon_GSM = "0471/664978", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Derykere ", Voornaam = "Frederick", Geboortedatum = DateTime.Parse("25/10/1971", new CultureInfo("de-DE")), Straatnaam = "Roodstaartplein", Straatnummer = "29", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Verstraete ", Voornaam = "Bianca", Geboortedatum = DateTime.Parse("21/12/1995", new CultureInfo("de-DE")), Straatnaam = "Roodstaartplein", Straatnummer = "29", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0474/531166", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Derykere ", Voornaam = "Bjorn", Geboortedatum = DateTime.Parse("14/01/2003", new CultureInfo("de-DE")), Straatnaam = "Roodstaartplein", Straatnummer = "29", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandevivere ", Voornaam = "Annick", Straatnaam = "Velodroomstraat", Straatnummer = "16A2A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0465/529202", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Rotsaert Amine ", Voornaam = "(kleinzoon)", Geboortedatum = DateTime.Parse("22/10/2005", new CultureInfo("de-DE")), Straatnaam = "Velodroomstraat", Straatnummer = "16A2A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Oosthuysse ", Voornaam = "Nancy", Geboortedatum = DateTime.Parse("05/07/1970", new CultureInfo("de-DE")), Straatnaam = "OLVrouwestraat", Straatnummer = "12", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0471/582141", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Verbeke ", Voornaam = "Peggy", Geboortedatum = DateTime.Parse("10/12/1974", new CultureInfo("de-DE")), Straatnaam = "Sportstraat", Straatnummer = "19", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "O57/360029", Telefoon_GSM = "0468/428476", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Verhenne ", Voornaam = "Logan", Geboortedatum = DateTime.Parse("12/02/2009", new CultureInfo("de-DE")), Straatnaam = "Sportstraat", Straatnummer = "19", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Desutter ", Voornaam = "Ginette", Geboortedatum = DateTime.Parse("20/02/1964", new CultureInfo("de-DE")), Straatnaam = "Aalmoezenierssraat", Straatnummer = "20c36", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0473/482040", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Dequirez ", Voornaam = "Serge", Geboortedatum = DateTime.Parse("22/01/1960", new CultureInfo("de-DE")), Straatnaam = "Velodromstraat", Straatnummer = "8", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bouchaert ", Voornaam = "Rosette", Geboortedatum = DateTime.Parse("31/01/1948", new CultureInfo("de-DE")), Straatnaam = "Tybaertstraat", Straatnummer = "12", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/205885", Telefoon_GSM = "0476/364165", Email = "rosette.bouchaert@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Van De Kerckhoven ", Voornaam = "Marni", Geboortedatum = DateTime.Parse("26/09/1968", new CultureInfo("de-DE")), Straatnaam = "Lindendreef", Straatnummer = "34", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0471/540991", Email = "Papavdk@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Van De Kerckhoven ", Voornaam = "Sascha", Geboortedatum = DateTime.Parse("18/01/2007", new CultureInfo("de-DE")), Straatnaam = "Azalealaan", Straatnummer = "14", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Van De Kerckhoven ", Voornaam = "Dylan", Geboortedatum = DateTime.Parse("04/04/2008", new CultureInfo("de-DE")), Straatnaam = "Azalealaan", Straatnummer = "14", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Deroy ", Voornaam = "Trees", Geboortedatum = DateTime.Parse("21/08/1957", new CultureInfo("de-DE")), Straatnaam = "Posthoornstraat", Straatnummer = "49", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0494/455196", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vuylsteke ", Voornaam = "Chris", Geboortedatum = DateTime.Parse("12/04/1963", new CultureInfo("de-DE")), Straatnaam = "Ieperleestraat", Straatnummer = "38", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0491/363548", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Catteau ", Voornaam = "Christophe", Geboortedatum = DateTime.Parse("12/08/1974", new CultureInfo("de-DE")), Straatnaam = "Rodenbachstraat", Straatnummer = "35", Postcode = 8908, Gemeente = "Vlamertinge", Telefoon_vast = "057/216820", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Balen ", Voornaam = "Florence", Geboortedatum = DateTime.Parse("11/02/1979", new CultureInfo("de-DE")), Straatnaam = "Rodenbachstraat", Straatnummer = "35", Postcode = 8908, Gemeente = "Vlamertinge", Telefoon_vast = "", Telefoon_GSM = "0495/569874", Email = "FlorenceCatteau@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Catteau ", Voornaam = "Jorden", Geboortedatum = DateTime.Parse("18/11/2008", new CultureInfo("de-DE")), Straatnaam = "Rodenbachstraat", Straatnummer = "35", Postcode = 8908, Gemeente = "Vlamertinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Crombez ", Voornaam = "Debora", Geboortedatum = DateTime.Parse("01/06/1981", new CultureInfo("de-DE")), Straatnaam = "Streuvelswijk", Straatnummer = "101", Postcode = 8908, Gemeente = "Vlamertinge", Telefoon_vast = "", Telefoon_GSM = "0493/914847", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Detrez ", Voornaam = "David", Geboortedatum = DateTime.Parse("07/09/2007", new CultureInfo("de-DE")), Straatnaam = "Streuvelswijk", Straatnummer = "101", Postcode = 8908, Gemeente = "Vlamertinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "ilunadetrez@outlook.com" });
            _context.Leden.Add(new Lid { Achternaam = "Detrez ", Voornaam = "Iluna", Geboortedatum = DateTime.Parse("19/08/2008", new CultureInfo("de-DE")), Straatnaam = "Streuvelswijk", Straatnummer = "101", Postcode = 8908, Gemeente = "Vlamertinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Detrez ", Voornaam = "Keano", Geboortedatum = DateTime.Parse("03/10/2011", new CultureInfo("de-DE")), Straatnaam = "Streuvelswijk", Straatnummer = "101", Postcode = 8908, Gemeente = "Vlamertinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Lefever ", Voornaam = "Christophe", Geboortedatum = DateTime.Parse("25/09/1979", new CultureInfo("de-DE")), Straatnaam = "Streuvelswijk", Straatnummer = "101", Postcode = 8908, Gemeente = "Vlamertinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Ligneel ", Voornaam = "Ingrid", Geboortedatum = DateTime.Parse("17/02/1959", new CultureInfo("de-DE")), Straatnaam = "Zaalhof", Straatnummer = "10", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0471/239546", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Claerbout ", Voornaam = "Dorine", Geboortedatum = DateTime.Parse("21/02/1961", new CultureInfo("de-DE")), Straatnaam = "Poperingseweg", Straatnummer = "28A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0499/170664", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Nevejan ", Voornaam = "Ludwig", Geboortedatum = DateTime.Parse("04/12/1969", new CultureInfo("de-DE")), Straatnaam = "Ieperleestraat", Straatnummer = "46", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/368234", Telefoon_GSM = "0495/704758", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Adam ", Voornaam = "Priscillia", Geboortedatum = DateTime.Parse("28/02/1968", new CultureInfo("de-DE")), Straatnaam = "Dikkebusseweg", Straatnummer = "36", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0495/660287", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bouckenhooghe ", Voornaam = "Jade", Geboortedatum = DateTime.Parse("07/01/2013", new CultureInfo("de-DE")), Straatnaam = "Dikkebusseweg", Straatnummer = "36", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "prescillia_neufort@hotamil.com" });
            _context.Leden.Add(new Lid { Achternaam = "Bouckenhooghe ", Voornaam = "Faith", Geboortedatum = DateTime.Parse("19/10/2009", new CultureInfo("de-DE")), Straatnaam = "Dikkebusseweg", Straatnummer = "36", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Desramault ", Voornaam = "Liam", Geboortedatum = DateTime.Parse("16/11/2007", new CultureInfo("de-DE")), Straatnaam = "Dikkebusseweg", Straatnummer = "36", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Provoost ", Voornaam = "Björn", Geboortedatum = DateTime.Parse("08/04/1988", new CultureInfo("de-DE")), Straatnaam = "Dikkebusseweg", Straatnummer = "36", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Provoost ", Voornaam = "Quinten", Geboortedatum = DateTime.Parse("28/06/2010", new CultureInfo("de-DE")), Straatnaam = "Dikkebusseweg", Straatnummer = "36", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Adam ", Voornaam = "Michelle", Geboortedatum = DateTime.Parse("09/07/2018", new CultureInfo("de-DE")), Straatnaam = "Dikkebusseweg", Straatnummer = "36", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Provoost ", Voornaam = "Tjorren", Geboortedatum = DateTime.Parse("17/09/2012", new CultureInfo("de-DE")), Straatnaam = "Dikkebusseweg", Straatnummer = "36", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Notredame ", Voornaam = "Ginette", Geboortedatum = DateTime.Parse("17/07/1949", new CultureInfo("de-DE")), Straatnaam = "Narcissenlaan", Straatnummer = "2 4VF", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/421225", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Maghiels ", Voornaam = "Patrick", Geboortedatum = DateTime.Parse("11/01/1969", new CultureInfo("de-DE")), Straatnaam = "Westkaai", Straatnummer = "3/bus 3A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0479/972534", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Logghe ", Voornaam = "Shana", Geboortedatum = DateTime.Parse("22/07/1993", new CultureInfo("de-DE")), Straatnaam = "Tegelstraat", Straatnummer = "47", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0491/919454", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Mertens ", Voornaam = "Glenn", Geboortedatum = DateTime.Parse("05/10/1989", new CultureInfo("de-DE")), Straatnaam = "Tegelstraat", Straatnummer = "47", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Mertens ", Voornaam = "Vic", Geboortedatum = DateTime.Parse("10/10/2017", new CultureInfo("de-DE")), Straatnaam = "Tegelstraat", Straatnummer = "47", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Mertens ", Voornaam = "Iluna", Geboortedatum = DateTime.Parse("14/01/2014", new CultureInfo("de-DE")), Straatnaam = "Tegelstraat", Straatnummer = "47", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Mertens ", Voornaam = "Liam", Geboortedatum = DateTime.Parse("02/02/2016", new CultureInfo("de-DE")), Straatnaam = "Tegelstraat", Straatnummer = "47", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Tressy ", Voornaam = "Anglo", Geboortedatum = DateTime.Parse("11/07/1988", new CultureInfo("de-DE")), Straatnaam = "Azalealaan", Straatnummer = "8 glv 1A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0473/619259", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Tressy ", Voornaam = "Fleur", Geboortedatum = DateTime.Parse("04/06/2013", new CultureInfo("de-DE")), Straatnaam = "Azalealaan", Straatnummer = "8 glv 1A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Tressy ", Voornaam = "Diego", Geboortedatum = DateTime.Parse("16/07/2016", new CultureInfo("de-DE")), Straatnaam = "Azalealaan", Straatnummer = "8 glv 1A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Sypre ", Voornaam = "Crissy", Geboortedatum = DateTime.Parse("29/08/1990", new CultureInfo("de-DE")), Straatnaam = "Wervikstraat", Straatnummer = "25", Postcode = 8902, Gemeente = "Zillebeke", Telefoon_vast = "", Telefoon_GSM = "0468/179671", Email = "beaubeau482@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Sypre ", Voornaam = "Cara", Geboortedatum = DateTime.Parse("19/11/2013", new CultureInfo("de-DE")), Straatnaam = "Wervikstraat", Straatnummer = "25", Postcode = 8902, Gemeente = "Zillebeke", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bouten ", Voornaam = "Luc", Straatnaam = "Posthoornstraat", Straatnummer = "47 glv", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0497/941407", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = " ", Voornaam = "Nicole", Straatnaam = "", Straatnummer = "", Gemeente = "", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Desomer ", Voornaam = "Paul", Straatnaam = "", Straatnummer = "", Gemeente = "", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Devos ", Voornaam = "Roos", Geboortedatum = DateTime.Parse("03/06/1947", new CultureInfo("de-DE")), Straatnaam = "Stoffelstraat", Straatnummer = "28 5C", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/209389", Telefoon_GSM = "0472/907127", Email = "roos.devos@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Huyse ", Voornaam = "Veronique", Geboortedatum = DateTime.Parse("06/02/1971", new CultureInfo("de-DE")), Straatnaam = "Kleine Pennestraat", Straatnummer = "10", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0474/282190", Email = "huyseveronique@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Sanders ", Voornaam = "Jan", Geboortedatum = DateTime.Parse("08/05/1947", new CultureInfo("de-DE")), Straatnaam = "Brugseweg", Straatnummer = "67/1B", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/366895", Telefoon_GSM = "0496/060728", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vrouwenopvang ", Voornaam = "", Straatnaam = "Brugseweg", Straatnummer = "?", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/219411", Telefoon_GSM = "", Email = "tine.welvaert@cawcentraalwestvlaanderen.be" });
            _context.Leden.Add(new Lid { Achternaam = "Hermans ", Voornaam = "Martine", Geboortedatum = DateTime.Parse("18/11/1965", new CultureInfo("de-DE")), Straatnaam = "Weverijstraat", Straatnummer = "19", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0471/265986", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = " ", Voornaam = "Julia", Straatnaam = "", Straatnummer = "", Gemeente = "", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = " ", Voornaam = "Donita", Straatnaam = "", Straatnummer = "", Gemeente = "", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Cailieau ", Voornaam = "", Geboortedatum = DateTime.Parse("11/03/1946", new CultureInfo("de-DE")), Straatnaam = "Paddevijverstraat", Straatnummer = "15", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0478/292230", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Anny ", Voornaam = "Lemaire", Geboortedatum = DateTime.Parse("21/10/1943", new CultureInfo("de-DE")), Straatnaam = "Kleine Pennesraat", Straatnummer = "19", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/366842", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Verstraete ", Voornaam = "Romy", Geboortedatum = DateTime.Parse("01/08/1991", new CultureInfo("de-DE")), Straatnaam = "Hoge Weide", Straatnummer = "39", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "0478/292230", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bisschop ", Voornaam = "Guillaume", Straatnaam = "Hoge Weide", Straatnummer = "39", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vanderstraeten ", Voornaam = "Gohan", Geboortedatum = DateTime.Parse("08/07/2012", new CultureInfo("de-DE")), Straatnaam = "Hoge Weide", Straatnummer = "39", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vanderstraeten ", Voornaam = "Raiden", Geboortedatum = DateTime.Parse("19/07/2014", new CultureInfo("de-DE")), Straatnaam = "Hoge Weide", Straatnummer = "39", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bisschop ", Voornaam = "Livay", Geboortedatum = DateTime.Parse("25/07/2018", new CultureInfo("de-DE")), Straatnaam = "Hoge Weide", Straatnummer = "39", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Barbez M. ", Voornaam = "Christine", Geboortedatum = DateTime.Parse("19/01/1960", new CultureInfo("de-DE")), Straatnaam = "Rijke Klarenstraat", Straatnummer = "75 1a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0485/947352", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Kiôefer ", Voornaam = "Dennis", Straatnaam = "Rijke Klarenstraat", Straatnummer = "75 2a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandamme ", Voornaam = "Francine", Geboortedatum = DateTime.Parse("28/02/1947", new CultureInfo("de-DE")), Straatnaam = "Veurnseweg", Straatnummer = "536", Postcode = 8906, Gemeente = "Elverdinge", Telefoon_vast = "057/422636", Telefoon_GSM = "0499/291709", Email = "Francine.vandamme@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Jaumain ", Voornaam = "Philip", Geboortedatum = DateTime.Parse("14/11/1969", new CultureInfo("de-DE")), Straatnaam = "d'Ennetiereplaats", Straatnummer = "14 A", Postcode = 8906, Gemeente = "Elverdinge", Telefoon_vast = "", Telefoon_GSM = "0497/026928", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Capoen ", Voornaam = "Els", Geboortedatum = DateTime.Parse("21/05/1973", new CultureInfo("de-DE")), Straatnaam = "Tuinweg", Straatnummer = "18", Postcode = 8906, Gemeente = "Elverdinge", Telefoon_vast = "057/206694", Telefoon_GSM = "0496/295028", Email = "elscapoen7305@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Vuylsteke ", Voornaam = "Dominiek", Geboortedatum = DateTime.Parse("30/03/1969", new CultureInfo("de-DE")), Straatnaam = "Tuinweg", Straatnummer = "18", Postcode = 8906, Gemeente = "Elverdinge", Telefoon_vast = "057/206694", Telefoon_GSM = "57", Email = "dominiek.vuylsteke@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Gerard ", Voornaam = "Termote", Geboortedatum = DateTime.Parse("04/04/1949", new CultureInfo("de-DE")), Straatnaam = "Steenstraat", Straatnummer = "14", Postcode = 8906, Gemeente = "Elverdinge", Telefoon_vast = "", Telefoon_GSM = "0470/632851", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Beun ", Voornaam = "Luc", Geboortedatum = DateTime.Parse("03/10/1968", new CultureInfo("de-DE")), Straatnaam = "St.Jorrisstraat", Straatnummer = "51", Postcode = 8906, Gemeente = "Elverdinge", Telefoon_vast = "057/212217", Telefoon_GSM = "0497/769486", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Debruyne ", Voornaam = "Dolores", Geboortedatum = DateTime.Parse("02/06/1971", new CultureInfo("de-DE")), Straatnaam = "St.Jorisstraat", Straatnummer = "52", Postcode = 8906, Gemeente = "Elverdinge", Telefoon_vast = "", Telefoon_GSM = "0472/327348", Email = ".dolores.debruyne@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Vandamme ", Voornaam = "Bart", Geboortedatum = DateTime.Parse("05/05/1980", new CultureInfo("de-DE")), Straatnaam = "Brugstraat", Straatnummer = "5", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "0498/520070", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Huyghe ", Voornaam = "Els", Geboortedatum = DateTime.Parse("06/07/1983", new CultureInfo("de-DE")), Straatnaam = "Brugstraat", Straatnummer = "5", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "eske05hotmail.be" });
            _context.Leden.Add(new Lid { Achternaam = "Vandamme ", Voornaam = "Kyliano", Geboortedatum = DateTime.Parse("11/05/2013", new CultureInfo("de-DE")), Straatnaam = "Brugstraat", Straatnummer = "5", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Goethals ", Voornaam = "Wout", Geboortedatum = DateTime.Parse("28/12/1964", new CultureInfo("de-DE")), Straatnaam = "Tulpenlaan", Straatnummer = "49/5", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0495/324002", Email = "Wout.goethals@skynet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Vandewalle ", Voornaam = "Patrick", Geboortedatum = DateTime.Parse("12/01/1959", new CultureInfo("de-DE")), Straatnaam = "Aalmoezenierstraat", Straatnummer = "20 bus 31", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0471/231018", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Verbrugge ", Voornaam = "Franky", Geboortedatum = DateTime.Parse("20/06/1961", new CultureInfo("de-DE")), Straatnaam = "Aalmoezenierstraat", Straatnummer = "20 bus 20", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0486/395347", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Morisse ", Voornaam = "Jean-Marie", Geboortedatum = DateTime.Parse("17/12/1950", new CultureInfo("de-DE")), Straatnaam = "Elisabethsttraat", Straatnummer = "2", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0497/817905", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Logghe ", Voornaam = "Jozef", Geboortedatum = DateTime.Parse("22/12/1957", new CultureInfo("de-DE")), Straatnaam = "Aalmoezeniersstraat", Straatnummer = "B53", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandenabeele ", Voornaam = "Eric", Geboortedatum = DateTime.Parse("20/02/1956", new CultureInfo("de-DE")), Straatnaam = "Bukkerstraat", Straatnummer = "C1", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/357964", Telefoon_GSM = "0477/438180", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Al Qotalski ", Voornaam = "Amer", Straatnaam = "Lange Meers", Straatnummer = "10", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0466/451324", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Al Qotalski ", Voornaam = "Ritja", Geboortedatum = DateTime.Parse("21/11/2009", new CultureInfo("de-DE")), Straatnaam = "Lange Meers", Straatnummer = "10", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Al Qotalski ", Voornaam = "Marjes", Geboortedatum = DateTime.Parse("04/09/2011", new CultureInfo("de-DE")), Straatnaam = "Lange Meers", Straatnummer = "10", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Al Qotalski ", Voornaam = "Rimas", Geboortedatum = DateTime.Parse("16/02/2013", new CultureInfo("de-DE")), Straatnaam = "Lange Meers", Straatnummer = "10", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Desmytere ", Voornaam = "Sylvianne", Geboortedatum = DateTime.Parse("25/01/1960", new CultureInfo("de-DE")), Straatnaam = "Aalmoesenierstraat", Straatnummer = "20 bus 49", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0492/646072", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vanbeselaere ", Voornaam = "Jan", Geboortedatum = DateTime.Parse("01/12/1953", new CultureInfo("de-DE")), Straatnaam = "Frezenbergstraat", Straatnummer = "18", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/207666", Telefoon_GSM = "0468/129811", Email = "jan.vanbeselaere@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Boone ", Voornaam = "Dirk", Geboortedatum = DateTime.Parse("03/01/1971", new CultureInfo("de-DE")), Straatnaam = "Tramstraat", Straatnummer = "30/2H", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0492/694626", Email = "boonedirk19@Gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Vereecke ", Voornaam = "Patrick", Geboortedatum = DateTime.Parse("07/10/1959", new CultureInfo("de-DE")), Straatnaam = "Poperingseweg", Straatnummer = "4", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0495/880343", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vanrenterghem ", Voornaam = "Walter", Geboortedatum = DateTime.Parse("26/03/1944", new CultureInfo("de-DE")), Straatnaam = "Poperingseweg", Straatnummer = "71", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "O57/208879", Telefoon_GSM = "0473/348776", Email = "vaste telefoon in huis" });
            _context.Leden.Add(new Lid { Achternaam = "Alleman ", Voornaam = "Eddy", Geboortedatum = DateTime.Parse("06/02/1967", new CultureInfo("de-DE")), Straatnaam = "Fiersstrat", Straatnummer = "4 1A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0492/750471", Email = "waterman_6267@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Rico ", Voornaam = "Vanhaverbeke", Geboortedatum = DateTime.Parse("02/06/1968", new CultureInfo("de-DE")), Straatnaam = "Oude Veurnestraat", Straatnummer = "49 2a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0491/201593", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandenkerchove ", Voornaam = "Bruce", Geboortedatum = DateTime.Parse("12/07/1989", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Van Der Paelt ", Voornaam = "Sylvie", Geboortedatum = DateTime.Parse("26/08/1978", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "0474/168806", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bonte ", Voornaam = "Giovanni", Geboortedatum = DateTime.Parse("05/04/2001", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "devonbonte@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Bonte ", Voornaam = "Dylan", Geboortedatum = DateTime.Parse("08/10/2003", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bonte ", Voornaam = "Jordy", Geboortedatum = DateTime.Parse("20/09/2004", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bonte ", Voornaam = "Femke", Geboortedatum = DateTime.Parse("04/06/2007", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bonte ", Voornaam = "Devon", Geboortedatum = DateTime.Parse("12/07/2008", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bonte ", Voornaam = "Keano", Geboortedatum = DateTime.Parse("03/08/2010", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bonte ", Voornaam = "Jolien", Geboortedatum = DateTime.Parse("19/11/2012", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bonte ", Voornaam = "Laura", Geboortedatum = DateTime.Parse("01/08/2014", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandekerckhove ", Voornaam = "Lucas", Geboortedatum = DateTime.Parse("25/01/2017", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandekerckhove ", Voornaam = "Julie", Geboortedatum = DateTime.Parse("20/10/2018", new CultureInfo("de-DE")), Straatnaam = "Wijtschaatsestraat", Straatnummer = "27", Postcode = 8902, Gemeente = "Voormezele", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Sintobin ", Voornaam = "Kurt", Geboortedatum = DateTime.Parse("14/01/1963", new CultureInfo("de-DE")), Straatnaam = "Pilkemstraat", Straatnummer = "3", Postcode = 8920, Gemeente = "Bikschote", Telefoon_vast = "051/726863", Telefoon_GSM = "", Email = "kurt.sintobin@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Pacco ", Voornaam = "Geertrui", Geboortedatum = DateTime.Parse("30/10/1975", new CultureInfo("de-DE")), Straatnaam = "Pilkemstraat", Straatnummer = "3", Postcode = 8920, Gemeente = "Bikschote", Telefoon_vast = "", Telefoon_GSM = "0476/430333", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Sintobin ", Voornaam = "Jarno", Geboortedatum = DateTime.Parse("15/09/2006", new CultureInfo("de-DE")), Straatnaam = "Pilkemstraat", Straatnummer = "3", Postcode = 8920, Gemeente = "Bikschote", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Sintobin ", Voornaam = "Iris", Geboortedatum = DateTime.Parse("25/07/2003", new CultureInfo("de-DE")), Straatnaam = "Pilkemstraat", Straatnummer = "3", Postcode = 8920, Gemeente = "Bikschote", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Jaecques ", Voornaam = "Christine", Geboortedatum = DateTime.Parse("21/06/1957", new CultureInfo("de-DE")), Straatnaam = "Anjelierenlaan", Straatnummer = "30", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/209223", Telefoon_GSM = "", Email = "dany.dewilde@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Broecks ", Voornaam = "Linda", Geboortedatum = DateTime.Parse("24/02/1953", new CultureInfo("de-DE")), Straatnaam = "Augustijnestraat", Straatnummer = "1B/glv", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0473/493039", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Housset ", Voornaam = "Pascal", Geboortedatum = DateTime.Parse("06/11/1956", new CultureInfo("de-DE")), Straatnaam = "Posthoornstraat", Straatnummer = "61", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0468/325777", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "De Wilde ", Voornaam = "Daniël", Geboortedatum = DateTime.Parse("20/10/1948", new CultureInfo("de-DE")), Straatnaam = "Posthoornstraat", Straatnummer = "65", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/212217", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Florissoone ", Voornaam = "Nancy", Geboortedatum = DateTime.Parse("09/11/1971", new CultureInfo("de-DE")), Straatnaam = "Anjelierenlaan", Straatnummer = "25", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/366676", Telefoon_GSM = "0471/259548", Email = "nancy-florissoone@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Verbeke ", Voornaam = "Amelie", Geboortedatum = DateTime.Parse("27/09/2013", new CultureInfo("de-DE")), Straatnaam = "Anjelierenlaan", Straatnummer = "25", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Verbeke ", Voornaam = "Joselito", Geboortedatum = DateTime.Parse("20/01/1998", new CultureInfo("de-DE")), Straatnaam = "Anjelierenlaan", Straatnummer = "25", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandenberghe ", Voornaam = "Roos", Geboortedatum = DateTime.Parse("22/01/1955", new CultureInfo("de-DE")), Straatnaam = "Oude Vaartsraat", Straatnummer = "31A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/206362", Telefoon_GSM = "0477/059076", Email = "lucdespeghel@skynet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Asloev ", Voornaam = "Tornik", Geboortedatum = DateTime.Parse("10/06/1976", new CultureInfo("de-DE")), Straatnaam = "Plumerlaan", Straatnummer = "79 2a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "ABASJAN ", Voornaam = "Anik", Geboortedatum = DateTime.Parse("08/09/1985", new CultureInfo("de-DE")), Straatnaam = "Plumerlaan", Straatnummer = "79 2a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0467/765149", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Asloev ", Voornaam = "David", Geboortedatum = DateTime.Parse("15/07/2010", new CultureInfo("de-DE")), Straatnaam = "Plumerlaan", Straatnummer = "79 2a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Asloev ", Voornaam = "Maxim", Geboortedatum = DateTime.Parse("06/12/2011", new CultureInfo("de-DE")), Straatnaam = "Plumerlaan", Straatnummer = "79 2a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Asloev ", Voornaam = "Diaana", Geboortedatum = DateTime.Parse("20/03/2013", new CultureInfo("de-DE")), Straatnaam = "Plumerlaan", Straatnummer = "79 2a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Asloev ", Voornaam = "Sara", Geboortedatum = DateTime.Parse("30/12/2017", new CultureInfo("de-DE")), Straatnaam = "Plumerlaan", Straatnummer = "79 2a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vanhee ", Voornaam = "Marnick", Geboortedatum = DateTime.Parse("23/11/1963", new CultureInfo("de-DE")), Straatnaam = "Goesdamstraat", Straatnummer = "3 bus 4a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Gombeer ", Voornaam = "Carine", Geboortedatum = DateTime.Parse("22/12/1965", new CultureInfo("de-DE")), Straatnaam = "Goesdamstraat", Straatnummer = "3 bus 4a", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0496/049780", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Van Den Kerckhove ", Voornaam = "Evelyn", Geboortedatum = DateTime.Parse("30/09/1993", new CultureInfo("de-DE")), Straatnaam = "Poperingseweg", Straatnummer = "28 B", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0470/878121", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Detailieur ", Voornaam = "Heidi", Geboortedatum = DateTime.Parse("24/04/1972", new CultureInfo("de-DE")), Straatnaam = "Graafschapstraat", Straatnummer = "12", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/209970", Telefoon_GSM = "0484/146505", Email = "heidi.detailleur@vives.be" });
            _context.Leden.Add(new Lid { Achternaam = "vriendWendy ", Voornaam = "Anthony", Geboortedatum = DateTime.Parse("04/01/1983", new CultureInfo("de-DE")), Straatnaam = "Zorgvlietstraat", Straatnummer = "18", Postcode = 8904, Gemeente = "Dikkebus", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandeputte ", Voornaam = "Wendy", Geboortedatum = DateTime.Parse("06/02/1984", new CultureInfo("de-DE")), Straatnaam = "Zorgvlietstraat", Straatnummer = "18", Postcode = 8904, Gemeente = "Dikkebus", Telefoon_vast = "", Telefoon_GSM = "0474/230103", Email = "kaykitravian@live.be" });
            _context.Leden.Add(new Lid { Achternaam = "Vandeputte ", Voornaam = "Kayenta", Geboortedatum = DateTime.Parse("24/03/2002", new CultureInfo("de-DE")), Straatnaam = "Zorgvlietstraat", Straatnummer = "18", Postcode = 8904, Gemeente = "Dikkebus", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandeputte ", Voornaam = "Allysia", Geboortedatum = DateTime.Parse("19/12/2008", new CultureInfo("de-DE")), Straatnaam = "Zorgvlietstraat", Straatnummer = "18", Postcode = 8904, Gemeente = "Dikkebus", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandeputte ", Voornaam = "Kitano", Geboortedatum = DateTime.Parse("16/10/2006", new CultureInfo("de-DE")), Straatnaam = "Zorgvlietstraat", Straatnummer = "18", Postcode = 8904, Gemeente = "Dikkebus", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandeputte ", Voornaam = "Elias", Geboortedatum = DateTime.Parse("07/08/2013", new CultureInfo("de-DE")), Straatnaam = "Zorgvlietstraat", Straatnummer = "18", Postcode = 8904, Gemeente = "Dikkebus", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Vandeputte ", Voornaam = "Djayden", Geboortedatum = DateTime.Parse("04/12/2009", new CultureInfo("de-DE")), Straatnaam = "Zorgvlietstraat", Straatnummer = "18", Postcode = 8904, Gemeente = "Dikkebus", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Decrop ", Voornaam = "Monique", Geboortedatum = DateTime.Parse("21/07/1956", new CultureInfo("de-DE")), Straatnaam = "Oudeveurnestraat", Straatnummer = "65 2b", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0498/540898", Email = "moniquedecrop56gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Vandenberghe ", Voornaam = "Carla", Geboortedatum = DateTime.Parse("09/12/1966", new CultureInfo("de-DE")), Straatnaam = "St.Jakobsnieuwweg", Straatnummer = "11", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0460/954877", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Bjorn ", Voornaam = "Symons", Geboortedatum = DateTime.Parse("29/09/1994", new CultureInfo("de-DE")), Straatnaam = "St.Jakobsnieuwweg", Straatnummer = "11", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Geldhof ", Voornaam = "Rosette", Geboortedatum = DateTime.Parse("23/10/1953", new CultureInfo("de-DE")), Straatnaam = "Paddepoelstraat", Straatnummer = "9", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/365139", Telefoon_GSM = "0494/332414", Email = "RosetteGeldhof@synet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Annemie ", Voornaam = "(boekje)", Straatnaam = "", Straatnummer = "", Gemeente = "", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Katrien ", Voornaam = "(boekje)", Straatnaam = "", Straatnummer = "", Gemeente = "", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Van Belle ", Voornaam = "Tania", Geboortedatum = DateTime.Parse("05/02/1977", new CultureInfo("de-DE")), Straatnaam = "Bloemendale", Straatnummer = "46", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "0467/052782", Email = "taniavanbelle24@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Van Belle ", Voornaam = "Branco", Geboortedatum = DateTime.Parse("27/07/2010", new CultureInfo("de-DE")), Straatnaam = "Bloemendale", Straatnummer = "46", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Van Belle ", Voornaam = "Brianna", Geboortedatum = DateTime.Parse("04/01/2017", new CultureInfo("de-DE")), Straatnaam = "Bloemendale", Straatnummer = "46", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Van Belle ", Voornaam = "Brian", Geboortedatum = DateTime.Parse("15/05/2018", new CultureInfo("de-DE")), Straatnaam = "Bloemendale", Straatnummer = "46", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Stepanie ", Voornaam = "Vercamer", Geboortedatum = DateTime.Parse("19/11/1989", new CultureInfo("de-DE")), Straatnaam = "Kasteelstraat", Straatnummer = "13", Postcode = 8908, Gemeente = "Vlamertine", Telefoon_vast = "", Telefoon_GSM = "0492/168387", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Killian ", Voornaam = "Six", Geboortedatum = DateTime.Parse("22/04/2007", new CultureInfo("de-DE")), Straatnaam = "Kasteelstraat", Straatnummer = "13", Postcode = 8908, Gemeente = "Vlamertine", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Six ", Voornaam = "Mila", Geboortedatum = DateTime.Parse("08/08/2013", new CultureInfo("de-DE")), Straatnaam = "Kasteelstraat", Straatnummer = "13", Postcode = 8908, Gemeente = "Vlamertine", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Deleu ", Voornaam = "Nancy", Geboortedatum = DateTime.Parse("08/02/1968", new CultureInfo("de-DE")), Straatnaam = "Bloemendaal", Straatnummer = "44", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "057/364694", Telefoon_GSM = "0470/537131", Email = "deleunancy1gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Duflourq ", Voornaam = "Sandra", Geboortedatum = DateTime.Parse("22/07/1988", new CultureInfo("de-DE")), Straatnaam = "Bloemendaal", Straatnummer = "44", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Duflorq ", Voornaam = "Kevin", Geboortedatum = DateTime.Parse("12/12/1994", new CultureInfo("de-DE")), Straatnaam = "Bloemendaal", Straatnummer = "44", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Caerels ", Voornaam = "Katleen", Geboortedatum = DateTime.Parse("09/08/1964", new CultureInfo("de-DE")), Straatnaam = "Du Parcwijk", Straatnummer = "11", Postcode = 8908, Gemeente = "Vlamertine", Telefoon_vast = "", Telefoon_GSM = "0468/200206", Email = "Kaatjrcaerels@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Mestdagh ", Voornaam = "Elsje", Straatnaam = "Hoge Weide", Straatnummer = "24", Postcode = 8904, Gemeente = "Boezinge", Telefoon_vast = "", Telefoon_GSM = "", Email = "elsje.mestdagh@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Vermandel ", Voornaam = "Nadine", Geboortedatum = DateTime.Parse("02/09/1970", new CultureInfo("de-DE")), Straatnaam = "Diksmuidseweg", Straatnummer = "15", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0470/588988", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Ameele ", Voornaam = "Natacha", Geboortedatum = DateTime.Parse("20/06/1982", new CultureInfo("de-DE")), Straatnaam = "Oude Veurnestraat", Straatnummer = "69 glv", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0473/380956", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Welleman ", Voornaam = "Graciano", Geboortedatum = DateTime.Parse("18/07/2018", new CultureInfo("de-DE")), Straatnaam = "Oude Veurnestraat", Straatnummer = "69 glv", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "", Email = "" });
            _context.Leden.Add(new Lid { Achternaam = "Decrop ", Voornaam = "Monique", Straatnaam = "Janseniuslaan", Straatnummer = "13 3B", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0498/540898", Email = "moniquedecrop56gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Vandenberghe ", Voornaam = "Roos", Straatnaam = "Oude Vaartstraat", Straatnummer = "31A", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0477/059076", Email = "lucdespeghel@skynet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Goethals ", Voornaam = "Wout", Straatnaam = "Tulpenlaan", Straatnummer = "49/5", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0495/324002", Email = "Wout.goethals@skynet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Devos ", Voornaam = "Roos", Straatnaam = "Stoffelstraat", Straatnummer = "28 5C", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "", Telefoon_GSM = "0472/907127", Email = "roos.devos@telenet.be" });
            _context.Leden.Add(new Lid { Achternaam = "Francine ", Voornaam = "Vandamme", Straatnaam = "Veurnseweg", Straatnummer = "536", Postcode = 8906, Gemeente = "Elverdinge", Telefoon_vast = "", Telefoon_GSM = "0499/291709", Email = "Francine.vandamme@gmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Kris ", Voornaam = "Reynaert", Straatnaam = "Frezenbergstraat", Straatnummer = "18", Postcode = 8900, Gemeente = "Ieper", Telefoon_vast = "057/207666", Telefoon_GSM = "0473/642032", Email = "krisreynaert@hotmail.com" });
            _context.Leden.Add(new Lid { Achternaam = "Sylviane ", Voornaam = "Roetynck", Straatnaam = "Wervikstraat", Straatnummer = "", Postcode = 8940, Gemeente = "Wervik", Telefoon_vast = "", Telefoon_GSM = "0473/755452", Email = "sylvianne.roetynck@telenet.be" });
            await _context.SaveChangesAsync();
            strStatus = "Leden zijn aangemaakt";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DelOntmoetingsplaatsen()
        {
            _context.Ontmoetingsplaatsen.RemoveRange(_context.Ontmoetingsplaatsen);
            await _context.SaveChangesAsync();
            strStatus = "Ontmoetingsplaatsen zijn gewist";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> SeedOntmoetingsplaatsen()
        {
            _context.Ontmoetingsplaatsen.Add(new Ontmoetingsplaats { Plaatsnaam = "De Kersecorf", Straatnaam = "Rijkeklarenstraat", Straatnummer = "83", Postcode = 8900, Gemeente = "Ieper" });
            _context.Ontmoetingsplaatsen.Add(new Ontmoetingsplaats { Plaatsnaam = "Sint-Maartenskring", Straatnaam = "Langemeersstraat", Straatnummer = "26", Postcode = 8900, Gemeente = "Ieper" });
            _context.Ontmoetingsplaatsen.Add(new Ontmoetingsplaats { Plaatsnaam = "Het Perron", Straatnaam = "Fochlaan", Straatnummer = "1", Postcode = 8900, Gemeente = "Ieper" });
            _context.Ontmoetingsplaatsen.Add(new Ontmoetingsplaats { Plaatsnaam = "Familiekring", Straatnaam = "Crescendostraat", Straatnummer = "19", Postcode = 8900, Gemeente = "Ieper" });
            _context.Ontmoetingsplaatsen.Add(new Ontmoetingsplaats { Plaatsnaam = "De Palingbeek", Straatnaam = "Vaartstraat", Straatnummer = "7", Postcode = 8902, Gemeente = "Zillebeke" });
            await _context.SaveChangesAsync();
            strStatus = "Ontmoetingsplaatsen zijn opnieuw aangemaakt";
            return RedirectToAction("Index");
        }

        public IActionResult DelActiviteiten()
        {
            strStatus = "Activiteiten zijn gewist";
            return RedirectToAction("Index");
        }

        public IActionResult SeedActiviteiten()
        {
            strStatus = "Activiteiten zijn aangemaakt";
            return RedirectToAction("Index");
        }
    }
}
